version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
      time: "00:00"
    groups:
      cargo-semver-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "00:00"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: "00:00"
    groups:
      pip-semver-minor:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
