def minify(
    code: str,
    /,
    *,
    allow_noncompliant_unquoted_attribute_values: bool,
    allow_optimal_entities: bool,
    allow_removing_spaces_between_attributes: bool,
    keep_closing_tags: bool,
    keep_comments: bool,
    keep_html_and_head_opening_tags: bool,
    keep_input_type_text_attr: bool,
    keep_ssi_comments: bool,
    minify_css: bool,
    minify_doctype: bool,
    minify_js: bool,
    preserve_brace_template_syntax: bool,
    preserve_chevron_percent_template_syntax: bool,
    remove_bangs: bool,
    remove_processing_instructions: bool,
) -> str: ...
